export const _mock_job_details = {
  title: "Senior Frontend Developer (Vue.js",
  company_name: "Tek Experts · Lagos State, Nigeria (Hybrid) ",
  contract_type: "Full-time",
  level_required: "Mid-Senior level",
  location: "Remote",
  capacity: 452,
  applicant: 349,
  desc: "As a Senior Frontend Engineer, you will play a crucial role in developing innovative and cutting-edge user interfaces for our products. You will work closely with cross-functional teams including product managers, designers, and backend engineers to create exceptional user experiences. Join our dynamic and forward-thinking Product Innovations Team, and contribute to shaping the future of our products through innovative front-end solutions.",
  responsibilities:
    "Develop and implement high-quality, responsive, and interactive front-end solutions for our products, using the latest web technologies, including JavaScript frameworks (React /Vue Js) \nCollaborate with product managers and designers to understand requirements and translate them into functional and visually appealing user interfaces. \nParticipate in the entire software development lifecycle, from design and implementation to testing and deployment, ensuring high code quality, performance, and scalability.\nConduct code reviews, provide constructive feedback, and mentor junior engineers to foster a culture of continuous improvement and growth.\nShould be able work to autonomously, take initiative on daily tasks and lead hackathons \nStay up-to-date with the latest front-end development trends, tools, and best practices, and proactively recommend innovative solutions to enhance user experiences and drive product innovation.\nWork closely with backend engineers to integrate front-end components with server side logic, APIs, and databases, ensuring seamless data flow and optimal performance.\nOptimize web applications for maximum speed and scalability, ensuring a smooth and efficient user experience across different devices and browsers.\nCollaborate with cross-functional teams to identify and resolve technical challenges, troubleshoot issues, and implement solutions in a timely manner",
  qualifications:
    "Bachelor's degree or equivalent in Computer Science\nMinimum of 6 years' experience in frontend development\nStrong proficiency in JavaScript, and modern front-end frameworks (Vue.js preferably).\nExperience with responsive web design and mobile-first development principles.\nSolid understanding of web performance optimization techniques and best practices.\nProficient with version control systems (e.g., Git) and front-end build tools (e.g., Webpack, Gulp, or Grunt).\nExperience with unit testing frameworks (e.g., Jest, Enzyme, or Jasmine) and test-driven development practices.\nStrong problem-solving skills and the ability to work independently as well as collaboratively in a fast-paced, agile environment.\nExcellent communication and interpersonal skills, with the ability to effectively articulate technical concepts to non-technical stakeholders.\nAny experience with backend technologies (Node.js, Python, Java, etc.) and knowledge of RESTful APIs is a plus.\nFamiliarity with UX design principles and user-centered design methodologies is advantageous.\nA portfolio or links to previous work demonstrating your front-end development skills and projects is highly desirable.",
};
