import person8 from "public/person8.jpg";
import person2 from "public/person2.jpg";
import person3 from "public/person3.jpg";
import person4 from "public/person4.jpg";
import person5 from "public/person5.jpg";
import person7 from "public/person7.jpg";
import camera from "public/asset1.jpg";
import beerBetterThanWomen from "public/asset2.jpg";
import work_shop from "public/asset3.jpg";
import carImg from "public/asset4.jpg";
import vacation from "public/asset5.jpg";
import randomImages from "public/asset6.jpg";
import plant from "public/asset7.jpg";
import multiColors from "public/asset8.jpg";
import birthday_cake from "public/asset9.jpg";
import triangleImg from "public/asset10.jpg";
import fingerLock from "public/asset12.jpg";
import multiColors2 from "public/asset13.jpg";
import golfBalls from "public/asset14.jpg";
import bubbles from "public/asset15.jpg";
import peopleSun from "public/asset16.jpg";
import cuteAnimalAnimation from "public/asset17.jpg";
import dice from "public/asset18.jpg";
import streetTraffic from "public/asset19.jpg";
import peopleVationMountain from "public/asset20.jpg";
import image1 from "public/tech1.jpg";
import image2 from "public/tech2.webp";
import image3 from "public/tech3.webp";
import image4 from "public/tech4.jpg";
import sch1 from "public/sch1.jpg";
import sch2 from "public/sch2.jpg";
import sch3 from "public/sch3.jpg";
import sch4 from "public/sch4.jpg";
export const otherUserDetails = [
  {
    name: "Willie Johnston",
    user_name: "Caroline11",
    location: "Venince",
    website1: "bpsvvp.uk/favorites",
    phoneNumber: "982-123-423-122",
    header:
      "I am a software developer who loves to create near perfect solutions for my customers",
    about:
      "I started my journey inthe year 2022, so far, i have created several webapps and even some cross mobile apps using react and react native.",
    bio: "FullStack developer",
    profession: "Software engineer",
    company: "Microsoft",
    start_date: "Fri, 29 Nov 2022 20:07:50.701780000 UTC +00:00",
    followers_count: 11287,
    id: 2,
    followers_count: 3238,
    image: person8,
    studiedAt: "MIT",
    from: "Venince, Italy, Europe",
    post_count: 204,
    posts: [
      {
        created_at: "2023-10-15 08:30:00",
        creator_name: "Willie Johnston",
        isLiked: true,
        id: 0,
        text: "I went on a vacation with my family, and I took this beautiful portrait of a mountain top!! \n \n Check it out 😍",
        author_id: 1,
        likes_count: 2330931400,
        comments_count: 32514679110,
        creator_image: person8,
        image: vacation,
      },
      {
        created_at: "2023-01-05 10:05:00",
        creator_name: "Willie Johnston",
        isLiked: false,
        id: 1,
        text: "Happy birthday to my beautiful baby boy! This year marks a +1 for him.... Don't let him see this, but this is his 7yr birthday :). \n Please, wish him an happy birthday",
        author_id: 2,
        likes_count: 66543693260,
        comments_count: 46625487324,
        creator_image: person8,
        image: birthday_cake,
      },
    ],
    experience: [
      {
        company_name: "DeCellar",
        id: 0,
        image: image1,
        desc: "Integrated smart contracts for users to interract with",
        title: "Blockchain Developer",
      },
      {
        company_name: "Microsoft",
        id: 1,
        image: image2,
        desc: "Improved the response time and cached datas for faster response",
        title: "Backend developer",
      },
      {
        company_name: "Goldman Sachs",
        id: 2,
        image: image3,
        desc: "Worked closely with UI designers to develop beautiful and fully responsive UIs",
        title: "Blockchain Developer",
      },
      {
        company_name: "DeCellar",
        id: 3,
        image: image4,
        desc: "Integrated smart contracts for users to interract with",
        title: "Blockchain Developer",
      },
    ],
    education: [
      {
        school_name: "Harvard",
        degree: "Masters",
        year: "2020",
        course: "Computer Engineering",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch1,
      },
      {
        school_name: "Oxford University",
        degree: "Phd",
        year: "2021",
        course: "Computer Science",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch2,
      },
      {
        school_name: "MIT",
        degree: "Bsc",
        year: "2016",
        course: "Computer Science",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch3,
      },
      {
        school_name: "Cambridge University",
        degree: "Diploma",
        year: "2020",
        course: "Computer Engineering",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch4,
      },
    ],
  },
  {
    name: "Mathilda Rice",
    user_name: "Lawrence36",
    location: "Bourdeux",
    website1: "bpsvvp.uk/favorites",
    phoneNumber: "982-123-423-122",
    header:
      "I am a software developer who loves to create near perfect solutions for my customers",
    about:
      "I started my journey inthe year 2022, so far, i have created several webapps and even some cross mobile apps using react and react native.",
    bio: "FullStack developer",
    profession: "Software engineer",
    company: "Microsoft",
    start_date: "Fri, 29 Nov 2022 20:07:50.701780000 UTC +00:00",
    followers_count: 25474,
    id: 3,
    following_count: 234,
    image: person7,
    studiedAt: "Oxford",
    from: "Marseille, France, Europe",
    post_count: 204,
    posts: [
      {
        created_at: "2023-04-03 15:55:00",
        creator_name: "Mathilda Rice",
        isLiked: true,
        id: 0,
        text: "Beautiful! Fell inlove with this wallpaper at first site 😍",
        author_id: 1,
        likes_count: 2330931400,
        comments_count: 32514679110,
        creator_image: person7,
        image: multiColors,
      },
      {
        created_at: "2023-05-20 20:30:00",
        creator_name: "Mathilda Rice",
        isLiked: false,
        id: 1,
        text: "Happy to see one of mother nature work! ",
        author_id: 2,
        likes_count: 66543693260,
        comments_count: 46625487324,
        creator_image: person7,
        image: plant,
      },
      {
        created_at: "2023-06-05 09:10:00",
        creator_name: "Mathilda Rice",
        isLiked: false,
        id: 2,
        text: "Beautiful piece by an amazing photographer! Me ;)",
        author_id: 2,
        likes_count: 66543693260,
        comments_count: 46625487324,
        creator_image: person7,
        image: golfBalls,
      },
    ],
    experience: [
      {
        company_name: "DeCellar",
        id: 1,
        image: image1,
        desc: "Integrated smart contracts for users to interract with",
        title: "Blockchain Developer",
      },
      {
        company_name: "Microsoft",
        id: 1,
        image: image2,
        desc: "Improved the response time and cached datas for faster response",
        title: "Backend developer",
      },
      {
        company_name: "Goldman Sachs",
        id: 1,
        image: image3,
        desc: "Worked closely with UI designers to develop beautiful and fully responsive UIs",
        title: "Blockchain Developer",
      },
      {
        company_name: "DeCellar",
        id: 1,
        image: image4,
        desc: "Integrated smart contracts for users to interract with",
        title: "Blockchain Developer",
      },
    ],
    education: [
      {
        school_name: "Harvard",
        degree: "Masters",
        year: "2020",
        course: "Computer Engineering",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch1,
      },
      {
        school_name: "Oxford University",
        degree: "Phd",
        year: "2021",
        course: "Computer Science",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch2,
      },
      {
        school_name: "MIT",
        degree: "Bsc",
        year: "2016",
        course: "Computer Science",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch3,
      },
      {
        school_name: "Cambridge University",
        degree: "Diploma",
        year: "2020",
        course: "Computer Engineering",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch4,
      },
    ],
  },
  {
    name: "Estelle Paul",
    user_name: "Dean5",
    location: "Paris",
    website1: "bpsvvp.uk/favorites",
    phoneNumber: "982-123-423-122",
    header:
      "I am a software developer who loves to create near perfect solutions for my customers",
    about:
      "I started my journey inthe year 2022, so far, i have created several webapps and even some cross mobile apps using react and react native.",
    bio: "FullStack developer",
    profession: "Software engineer",
    company: "Microsoft",
    start_date: "Fri, 29 Nov 2022 20:07:50.701780000 UTC +00:00",
    followers_count: 32456,
    id: 4,
    following_count: 2145,
    image: person2,
    studiedAt: "Cambridge",
    from: "Paris, France, Europe",
    post_count: 204,
    posts: [
      {
        created_at: "2023-06-05 09:10:00",
        creator_name: "Estelle Paul",
        isLiked: true,
        id: 0,
        text: "The beautiful partner behind all my great shots! 😍",
        author_id: 1,
        likes_count: 2330931400,
        comments_count: 32514679110,
        creator_image: person2,
        image: camera,
      },
      {
        created_at: "2023-07-12 18:20:00",
        creator_name: "Estelle Paul",
        isLiked: false,
        id: 1,
        text: "This got me feeling nostalgic! Played with a whole lots of bubble blowers whilst I was growing up!! \n I miss those days 😩",
        author_id: 2,
        likes_count: 66543693260,
        comments_count: 46625487324,
        creator_image: person2,
        image: bubbles,
      },
      {
        created_at: "2023-08-25 12:15:00",
        creator_name: "Estelle Paul",
        isLiked: true,
        id: 2,
        text: "When people ask me what probability means, I just show them an image of a dice!",
        author_id: 2,
        likes_count: 66543693260,
        comments_count: 46625487324,
        creator_image: person2,
        image: dice,
      },
    ],
    experience: [
      {
        company_name: "DeCellar",
        id: 1,
        image: image1,
        desc: "Integrated smart contracts for users to interract with",
        title: "Blockchain Developer",
      },
      {
        company_name: "Microsoft",
        id: 1,
        image: image2,
        desc: "Improved the response time and cached datas for faster response",
        title: "Backend developer",
      },
      {
        company_name: "Goldman Sachs",
        id: 1,
        image: image3,
        desc: "Worked closely with UI designers to develop beautiful and fully responsive UIs",
        title: "Blockchain Developer",
      },
      {
        company_name: "DeCellar",
        id: 1,
        image: image4,
        desc: "Integrated smart contracts for users to interract with",
        title: "Blockchain Developer",
      },
    ],
    education: [
      {
        school_name: "Harvard",
        degree: "Masters",
        year: "2020",
        course: "Computer Engineering",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch1,
      },
      {
        school_name: "Oxford University",
        degree: "Phd",
        year: "2021",
        course: "Computer Science",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch2,
      },
      {
        school_name: "MIT",
        degree: "Bsc",
        year: "2016",
        course: "Computer Science",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch3,
      },
      {
        school_name: "Cambridge University",
        degree: "Diploma",
        year: "2020",
        course: "Computer Engineering",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch4,
      },
    ],
  },
  {
    name: "Ralph Jensen",
    user_name: "Estella21",
    location: "Amsterdam",
    website1: "bpsvvp.uk/favorites",
    phoneNumber: "982-123-423-122",
    header:
      "I am a software developer who loves to create near perfect solutions for my customers",
    about:
      "I started my journey inthe year 2022, so far, i have created several webapps and even some cross mobile apps using react and react native.",
    bio: "FullStack developer",
    profession: "Software engineer",
    company: "Microsoft",
    start_date: "Fri, 29 Nov 2022 20:07:50.701780000 UTC +00:00",
    followers_count: 13232,
    id: 5,
    following_count: 124,
    image: person3,
    studiedAt: "Stanford University",
    from: "Amsterdam, Netherlands, Europe",
    post_count: 204,
    posts: [
      {
        created_at: "2023-10-15 08:30:00",
        creator_name: "Ralph Jensen",
        isLiked: true,
        id: 0,
        text: "I really can't wait to start my driving classes... who knows... maybe I could be in someone else's image ;)",
        author_id: 1,
        likes_count: 2330931400,
        comments_count: 32514679110,
        creator_image: person3,
        image: streetTraffic,
      },
      {
        created_at: "2023-09-30 14:45:00",
        creator_name: "Ralph Jensen",
        isLiked: false,
        id: 1,
        text: "Beautiful mix of colors",
        author_id: 2,
        likes_count: 66543693260,
        comments_count: 46625487324,
        creator_image: person3,
        image: multiColors2,
      },
      {
        created_at: "2023-08-25 12:15:00",
        creator_name: "Ralph Jensen",
        isLiked: true,
        id: 2,
        text: "This picture makes me miss the beautiful view of sunset in mountanious areas",
        author_id: 2,
        likes_count: 66543693260,
        comments_count: 46625487324,
        creator_image: person3,
        image: peopleSun,
      },
    ],
    experience: [
      {
        company_name: "DeCellar",
        id: 1,
        image: image1,
        desc: "Integrated smart contracts for users to interract with",
        title: "Blockchain Developer",
      },
      {
        company_name: "Microsoft",
        id: 1,
        image: image2,
        desc: "Improved the response time and cached datas for faster response",
        title: "Backend developer",
      },
      {
        company_name: "Goldman Sachs",
        id: 1,
        image: image3,
        desc: "Worked closely with UI designers to develop beautiful and fully responsive UIs",
        title: "Blockchain Developer",
      },
      {
        company_name: "DeCellar",
        id: 1,
        image: image4,
        desc: "Integrated smart contracts for users to interract with",
        title: "Blockchain Developer",
      },
      {
        company_name: "Goldman Sachs",
        id: 1,
        image: image3,
        desc: "Worked closely with UI designers to develop beautiful and fully responsive UIs",
        title: "Blockchain Developer",
      },
      {
        company_name: "DeCellar",
        id: 1,
        image: image4,
        desc: "Integrated smart contracts for users to interract with",
        title: "Blockchain Developer",
      },
    ],
    education: [
      {
        school_name: "Harvard",
        degree: "Masters",
        year: "2020",
        course: "Computer Engineering",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch1,
      },
      {
        school_name: "Oxford University",
        degree: "Phd",
        year: "2021",
        course: "Computer Science",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch2,
      },
      {
        school_name: "MIT",
        degree: "Bsc",
        year: "2016",
        course: "Computer Science",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch3,
      },
      {
        school_name: "Cambridge University",
        degree: "Diploma",
        year: "2020",
        course: "Computer Engineering",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch4,
      },
    ],
  },
  {
    name: "McLauren Ramos",
    user_name: "Katie29",
    location: "Rome",
    website1: "bpsvvp.uk/favorites",
    phoneNumber: "982-123-423-122",
    header:
      "I am a software developer who loves to create near perfect solutions for my customers",
    about:
      "I started my journey inthe year 2022, so far, i have created several webapps and even some cross mobile apps using react and react native.",
    bio: "FullStack developer",
    profession: "Software engineer",
    company: "Microsoft",
    start_date: "Fri, 29 Nov 2022 20:07:50.701780000 UTC +00:00",
    followers_count: 2343,
    id: 6,
    following_count: 45,
    image: person4,
    studiedAt: "University of Rome",
    from: "Venince, Italy, Europe",
    post_count: 204,
    posts: [
      {
        created_at: "2023-01-05 10:05:00",
        creator_name: "McLauren Ramos",
        isLiked: true,
        id: 0,
        text: "Pinky fingers! Beautiful pact!",
        author_id: 1,
        likes_count: 2330931400,
        comments_count: 32514679110,
        creator_image: person4,
        image: fingerLock,
      },
      {
        created_at: "2023-02-10 23:25:00",
        creator_name: "McLauren Ramos",
        isLiked: false,
        id: 1,
        text: "Tiny beautiful puny animal animation!",
        author_id: 2,
        likes_count: 66543693260,
        comments_count: 46625487324,
        creator_image: person4,
        image: cuteAnimalAnimation,
      },
      {
        created_at: "2023-04-03 15:55:00",
        creator_name: "McLauren Ramos",
        isLiked: true,
        id: 2,
        text: "I really miss these old days!!",
        author_id: 2,
        likes_count: 66543693260,
        comments_count: 46625487324,
        creator_image: person4,
        image: peopleVationMountain,
      },
      {
        created_at: "2023-06-05 09:10:00",
        creator_name: "McLauren Ramos",
        isLiked: true,
        id: 3,
        text: "This is a very beautiful piece... Hundreds of images with millions of meanings.",
        author_id: 2,
        likes_count: 66543693260,
        comments_count: 46625487324,
        creator_image: person4,
        image: randomImages,
      },
    ],
    experience: [
      {
        company_name: "DeCellar",
        id: 1,
        image: image1,
        desc: "Integrated smart contracts for users to interract with",
        title: "Blockchain Developer",
      },
      {
        company_name: "Microsoft",
        id: 1,
        image: image2,
        desc: "Improved the response time and cached datas for faster response",
        title: "Backend developer",
      },
      {
        company_name: "Goldman Sachs",
        id: 1,
        image: image3,
        desc: "Worked closely with UI designers to develop beautiful and fully responsive UIs",
        title: "Blockchain Developer",
      },
      {
        company_name: "DeCellar",
        id: 1,
        image: image4,
        desc: "Integrated smart contracts for users to interract with",
        title: "Blockchain Developer",
      },
    ],
    education: [
      {
        school_name: "Harvard",
        degree: "Masters",
        year: "2020",
        course: "Computer Engineering",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch1,
      },
      {
        school_name: "Oxford University",
        degree: "Phd",
        year: "2021",
        course: "Computer Science",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch2,
      },
      {
        school_name: "MIT",
        degree: "Bsc",
        year: "2016",
        course: "Computer Science",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch3,
      },
      {
        school_name: "Cambridge University",
        degree: "Diploma",
        year: "2020",
        course: "Computer Engineering",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch4,
      },
    ],
  },
  {
    name: "Christina Fox",
    user_name: "Katie29",
    location: "MAnnitoba, Canada",
    website1: "bpsvvp.uk/favorites",
    phoneNumber: "982-123-423-122",
    header:
      "I am a software developer who loves to create near perfect solutions for my customers",
    about:
      "I started my journey inthe year 2022, so far, i have created several webapps and even some cross mobile apps using react and react native.",
    bio: "FullStack developer",
    profession: "Software engineer",
    company: "Microsoft",
    start_date: "Fri, 29 Nov 2022 20:07:50.701780000 UTC +00:00",
    followers_count: 32352,
    id: 7,
    following_count: 21,
    image: person5,
    studiedAt: "University of Canada",
    from: "Ontairo, Canada",
    post_count: 204,
    posts: [
      {
        created_at: "2023-08-25 12:15:00",
        creator_name: "Christina Fox",
        isLiked: true,
        id: 0,
        text: "Damn! This car looks beautiful!... Guess what? This beauty came with great performance and a very top notch quality",
        author_id: 1,
        likes_count: 2330931400,
        comments_count: 32514679110,
        creator_image: person5,
        image: carImg,
      },
      {
        created_at: "2023-05-20 20:30:00",
        creator_name: "Christina Fox",
        isLiked: false,
        id: 1,
        text: "I came accross this workshop, and i thought it was captivating... Temp was quite alright and the hue balance was second to none. \n Here is the image",
        author_id: 2,
        likes_count: 66543693260,
        comments_count: 46625487324,
        creator_image: person5,
        image: work_shop,
      },
      {
        created_at: "2023-02-10 23:25:00",
        creator_name: "Christina Fox",
        isLiked: true,
        id: 2,
        text: "Another beautiful piece",
        author_id: 2,
        likes_count: 66543693260,
        comments_count: 46625487324,
        creator_image: person5,
        image: triangleImg,
      },
      {
        created_at: "2023-04-03 15:55:00",
        creator_name: "Christina Fox",
        isLiked: true,
        id: 3,
        text: "This looks and sounds true... But they wont agree 😂",
        author_id: 2,
        likes_count: 66543693260,
        comments_count: 46625487324,
        creator_image: person5,
        image: beerBetterThanWomen,
      },
    ],
    experience: [
      {
        company_name: "DeCellar",
        id: 1,
        image: image1,
        desc: "Integrated smart contracts for users to interract with",
        title: "Blockchain Developer",
      },
      {
        company_name: "Microsoft",
        id: 1,
        image: image2,
        desc: "Improved the response time and cached datas for faster response",
        title: "Backend developer",
      },
      {
        company_name: "Goldman Sachs",
        id: 1,
        image: image3,
        desc: "Worked closely with UI designers to develop beautiful and fully responsive UIs",
        title: "Blockchain Developer",
      },
      {
        company_name: "DeCellar",
        id: 1,
        image: image4,
        desc: "Integrated smart contracts for users to interract with",
        title: "Blockchain Developer",
      },
    ],
    education: [
      {
        school_name: "Harvard",
        degree: "Masters",
        year: "2020",
        course: "Computer Engineering",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch1,
      },
      {
        school_name: "Oxford University",
        degree: "Phd",
        year: "2021",
        course: "Computer Science",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch2,
      },
      {
        school_name: "MIT",
        degree: "Bsc",
        year: "2016",
        course: "Computer Science",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch3,
      },
      {
        school_name: "Cambridge University",
        degree: "Diploma",
        year: "2020",
        course: "Computer Engineering",
        desc: "Learnt Artificial intelligence and created several AI model to help solve algorithmic problems",
        img: sch4,
      },
    ],
  },
];
